version: '3.8'

services:
  postgres:
    image: postgres:15.0
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U denisromanov
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  
volumes:
  pg_data_todolist:
